// Generated by CoffeeScript 1.8.0
(function() {
  var abs, log, max, min, random, round;

  random = Math.random, round = Math.round, log = Math.log, abs = Math.abs, min = Math.min, max = Math.max;

  module.exports = function(text) {
    var a, i, last, n, p, suffix, _i;
    n = round(log((random()) * 100 + 2));
    p = 1 / 4;
    a = [round(random())];
    for (i = _i = 1; 1 <= n ? _i <= n : _i >= n; i = 1 <= n ? ++_i : --_i) {
      last = a[a.length - 1];
      a.push((random()) < p ? 1 - last : last);
    }
    suffix = a.map(function(x) {
      if (x === 0) {
        return '！';
      } else {
        return '？';
      }
    }).join('');
    return text + suffix;
  };

}).call(this);
