// Generated by CoffeeScript 1.7.1
(function() {
  var abs, append_marks, load, log, make, max, min, model_path, mutter, noun, pp, random, reply, round, _ref;

  pp = require('./poppush');

  noun = require('./noun');

  append_marks = require('./append_marks');

  _ref = require('./ngram'), load = _ref.load, make = _ref.make, model_path = _ref.model_path;

  random = Math.random, round = Math.round, log = Math.log, abs = Math.abs, min = Math.min, max = Math.max;

  load(model_path);

  reply = function(text, cont) {
    var msg, pr;
    text = text.replace(/@[\sa-zA-Z0-9_]*/g, '');
    text = text.trim();
    pr = random();
    if (pr < 0.3) {
      pp.pop(cont);
      return;
    }
    pr -= 0.3;
    if (pr < 0.3) {
      msg = make();
      cont(msg);
      return;
    }
    return noun(text, function(result) {
      if (result.status === 'successed') {
        return cont(result.msg);
      } else {
        msg = append_marks(text);
        return cont(msg);
      }
    });
  };

  mutter = function(cont) {
    var pr;
    pr = pp.popp();
    if (pr > 0.7) {
      return pp.pop(cont);
    } else {
      return cont(make());
    }
  };

  module.exports = {
    push: pp.push,
    reply: reply,
    mutter: mutter
  };

}).call(this);
