// Generated by CoffeeScript 1.7.1
(function() {
  var abs, exec, log, max, min, noun, random, round;

  exec = require('child_process').exec;

  random = Math.random, round = Math.round, log = Math.log, abs = Math.abs, min = Math.min, max = Math.max;

  noun = function(text, cont) {
    text = text.replace(/"/g, '').replace(/'/g, '');
    return exec("echo \"" + text + "\" | mecab", function(er, ls) {
      var n, nouns, suf, sufs;
      nouns = ls.split('\n').filter(function(l) {
        return (l.indexOf('\t名詞')) > 0;
      }).map(function(l) {
        return (l.split('\t'))[0];
      });
      if (nouns.length === 0) {
        cont({
          status: "failed"
        });
      }
      n = nouns.reduce(function(x, y) {
        if (x.length > y.length) {
          return x;
        } else {
          return y;
        }
      });
      if (n.length < 3) {
        cont({
          status: "failed"
        });
      }
      sufs = ['？', '...???', 'だね', 'か!!'];
      suf = sufs[sufs.length * (random()) | 0];
      return cont({
        status: "successed",
        msg: n + suf
      });
    });
  };

  module.exports = noun;

}).call(this);
