// Generated by CoffeeScript 1.7.1
(function() {
  var exec, main, zero;

  exec = require('child_process').exec;

  zero = function(x) {
    return ('00'.slice(x.length)) + x;
  };

  main = function(arg, cont) {
    var xs;
    switch (false) {
      case !((arg === null) || arg === ''):
        return exec("calendar -f ./calendar/voice.calendar", function(er, ou) {
          return cont(ou);
        });
      case !/^\d+\/\d+$/.test(arg):
        xs = arg.split('/');
        arg = (zero(xs[0])) + (zero(xs[1]));
        return main(arg, cont);
      case !/^\d{4}$/.test(arg):
        return exec("calendar -f ./calendar/voice.calendar -t " + arg, function(er, ou) {
          return cont(ou);
        });
      default:
        return exec("grep '" + arg + "' ./calendar/voice.calendar", function(er, ou) {
          return cont(ou);
        });
    }
  };

  module.exports = main;

}).call(this);
