// Generated by CoffeeScript 1.7.1
(function() {
  var exec, misdo;

  exec = require('child_process').exec;

  misdo = function(cont) {
    var findNow, url;
    findNow = function(ls) {
      var sub;
      sub = function(i) {
        if (ls[i].now === 'true') {
          return i;
        } else {
          return sub(i + 1);
        }
      };
      return sub(0);
    };
    url = 'http://sp.i-misdo.com/music/find.cgi?callback=displayCurrentlyMusic_Comments&mode=nowplaying';
    return exec("curl '" + url + "' |nkf", function(er, ou) {
      var i, idx, jdx, ls, str, the;
      idx = ou.indexOf('{');
      jdx = ou.lastIndexOf('}');
      str = ou.slice(idx, jdx + 1);
      ls = (JSON.parse(str)).list;
      i = findNow(ls);
      the = ls[i];
      return cont("" + the.artist + ": " + the.title + " from " + the.time);
    });
  };

  module.exports = misdo;

}).call(this);
